# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy source files
COPY . .

# Build the project
RUN npx tsc

# Expose any ports if needed, although MCP communicates over stdio

# Start the server
CMD ["node", "dist/index.js"]
